# Generated by Django 2.2.15 on 2020-08-20 04:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('regs', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='users',
            name='new',
            field=models.BooleanField(default=True),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='users',
            name='first_name',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='users',
            name='last_name',
            field=models.TextField(max_length=20),
        ),
    ]
