# Generated by Django 2.2.15 on 2020-08-21 04:34

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('regs', '0002_auto_20200820_0744'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='users',
            name='new',
        ),
        migrations.AddField(
            model_name='users',
            name='join_date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='users',
            name='last_name',
            field=models.CharField(max_length=20),
        ),
    ]
